enableGlobalCache: true

nodeLinker: node-modules

npmScopes:
  anonyome:
    npmPublishRegistry: 'https://repo.tools.anonyome.com/repository/npm-hosted/'
    npmRegistryServer: 'https://repo.tools.anonyome.com/repository/npm-hosted/'
  sudoplatform-private:
    npmPublishRegistry: 'https://repo.tools.anonyome.com/repository/npm-hosted/'
    npmRegistryServer: 'https://repo.tools.anonyome.com/repository/npm-hosted/'
