image: '947875592751.dkr.ecr.us-east-1.amazonaws.com/tools/node-build:${NODE_BUILD_VERSION}'

before_script:
  - node --version
  - corepack enable
  - yarn install --immutable

variables:
  YARN_NPM_AUTH_TOKEN: ${NEXUS_READ_TOKEN}

stages:
  - Secrets Test
  - Verify
  - Build
  - Publish

.publish_external:
  image: '947875592751.dkr.ecr.us-east-1.amazonaws.com/tools/node-build:${NODE_BUILD_VERSION}'
  stage: Publish
  variables:
    PUB_TAG: $CI_COMMIT_TAG
    PUB_GITHUB_ACCESS_TOKEN: $GITHUB_ACCESS_TOKEN
    PUB_GITLAB_ACCESS_TOKEN: $API_ACCESS_TOKEN
    PUB_DIST_TAG: $DIST_TAG
    PUB_TRUSTED_PUBLISH: true
    PUB_NO_RELEASE: true
    PUB_CUSTOM_BUILD_SCRIPT: |
      DEST_DIR="config"
      mkdir -p "$DEST_DIR"
      echo "{}" > "${DEST_DIR}/sudoplatformconfig.json"
      touch "${DEST_DIR}/register_key.private"
      touch "${DEST_DIR}/register_key.id"
  script:
    - corepack enable
    - yarn install --immutable
    - yarn dlx @sudoplatform-private/sdk-publisher@2.1.0-19-g39292ac-39292acf --verbose
  tags:
    - docker

secret-detection-repo:
  stage: Secrets Test
  before_script:
    - ''
  image:
    name: 947875592751.dkr.ecr.us-east-1.amazonaws.com/tools/secret-detection:latest
  script:
    - gitleaks-repo
  artifacts:
    when: on_failure
    paths:
      - secrets.json
  tags:
    - docker

Verify:
  stage: Verify
  script:
    - yarn verify
  tags:
    - docker

Build:
  stage: Build
  script:
    - corepack enable
    - yarn install --immutable
    - yarn clean
    - export DEST_DIR=config
    - mkdir -p $DEST_DIR
    - 'echo "{}" > "${DEST_DIR}/sudoplatformconfig.json"'
    - 'touch "${DEST_DIR}/register_key.private"'
    - 'touch "${DEST_DIR}/register_key.id"'
    - yarn build
  artifacts:
    paths:
      - build/
  tags:
    - docker

Beta:
  extends: .publish_external
  variables:
    DIST_TAG: beta
  only:
    - /beta/

Release:
  extends: .publish_external
  variables:
    DIST_TAG: latest
  only:
    - /^\d+\.\d+\.\d+$/
